name: build.yml

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Lint, test and build website
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
        working-directory: [./website]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        working-directory: ${{ matrix.working-directory }}
        run: yarn install

      - name: Lint project
        working-directory: ${{ matrix.working-directory }}
        run: yarn lint

      - name: Test project
        working-directory: ${{ matrix.working-directory }}
        run: yarn test

      - name: Generate website
        working-directory: ${{ matrix.working-directory }}
        run: yarn nuxt generate

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: LloydTao
          author_email: LL23@live.co.uk
          message: "Nuxt generate and commit"
          add: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
